FROM node:18-alpine

WORKDIR /app

COPY blog-service/package*.json ./
RUN npm ci --only=production

COPY blog-service/src ./src
COPY blog-service/.env.production .env

EXPOSE 3002

CMD ["node", "src/server.js"]
